from dotenv import load_dotenv
import os

load_dotenv()

# Applicant Details
APPLICANT_FIRST_NAME = os.getenv("APPLICANT_FIRST_NAME")
APPLICANT_LAST_NAME = os.getenv("APPLICANT_LAST_NAME")
APPLICANT_EMAIL = os.getenv("APPLICANT_EMAIL")
APPLICANT_PHONE = os.getenv("APPLICANT_PHONE")
APPLICANT_RESUME_PATH = os.getenv("APPLICANT_RESUME_PATH")
APPLICANT_LINKEDIN_URL = os.getenv("APPLICANT_LINKEDIN_URL")
APPLICANT_GITHUB_URL = os.getenv("APPLICANT_GITHUB_URL")
#APPLICANT_PORTFOLIO_URL = os.getenv("APPLICANT_PORTFOLIO_URL")
APPLICANT_DETAILS_PATH = os.getenv("APPLICANT_DETAILS_PATH")

# OpenAI API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Playwright config
USER_DATA_DIR = os.getenv("USER_DATA_DIR", "user_data") 