from dotenv import load_dotenv
import os

load_dotenv()

AWS_REGION = os.getenv("AWS_REGION", "us-east-1")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
SQS_QUEUE_URL = os.getenv("SQS_QUEUE_URL")
SQS_APPLY_QUEUE_URL = os.getenv("SQS_APPLY_QUEUE_URL")

# Google Sheets settings
GOOGLE_SHEET_NAME = os.getenv("GOOGLE_SHEET_NAME")
GOOGLE_SERVICE_ACCOUNT_CREDS = os.getenv("GOOGLE_SERVICE_ACCOUNT_CREDS") 

# Applicant Details
APPLICANT_FIRST_NAME = os.getenv("APPLICANT_FIRST_NAME")
APPLICANT_LAST_NAME = os.getenv("APPLICANT_LAST_NAME")
APPLICANT_EMAIL = os.getenv("APPLICANT_EMAIL")
APPLICANT_PHONE = os.getenv("APPLICANT_PHONE")
APPLICANT_RESUME_PATH = os.getenv("APPLICANT_RESUME_PATH")
APPLICANT_LINKEDIN_URL = os.getenv("APPLICANT_LINKEDIN_URL")
APPLICANT_GITHUB_URL = os.getenv("APPLICANT_GITHUB_URL")
APPLICANT_TWITTER_URL = os.getenv("APPLICANT_TWITTER_URL")
APPLICANT_DETAILS_PATH = os.getenv("APPLICANT_DETAILS_PATH")

# OpenAI API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Playwright config
USER_DATA_DIR = os.getenv("USER_DATA_DIR", "user_data") 